[workspace]
resolver = "1"
members = [
    "src/lib",
    "src/remittance",
    "src/data_collection",
    "src/protocol_data_collection",
    "src/examples/token",
    "src/examples/bridge_data_collection",
    "src/ic_af",
    "src/tlsn-substrings-verifier"
]
