[package]
name = "tlsn-substrings-verifier"
authors = ["TLSNotary Team | Usher Labs"]
description = "Core verifier lib for TLSNotary"
keywords = ["tls", "mpc", "2pc", "types"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.5"
edition = "2021"

[dependencies]
hex = "0.4.3"
rs_merkle = "1.4.2"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
mpz-core = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "9f7403b" }
mpz-garble-core = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "9f7403b" }
mpz-circuits = { git = "https://github.com/privacy-scaling-explorations/mpz", rev = "9f7403b" }
tlsn-utils = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "51f313d" }
thiserror = "1.0.59"
bincode = "1.3.3"
bytes = { version = "1.4", features = ["serde"] }
bimap = { version = "0.6.3", features = ["serde"] }
opaque-debug = "0.3.1"
p256 = { version = "0.13.2", features = ["serde"] }

[dev-dependencies]
rstest = "0.19.0"
# tlsn-core = { git = "https://github.com/tlsnotary/tlsn" }
