[package]
name = "ic_af"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.4"
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
ic-cdk-timers = "0.1.1"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0"
dotenv = "0.15.0"
tlsn-substrings-verifier = { path = "../tlsn-substrings-verifier" }
p256 = { version = "0.13.2", features = ["serde"] }
# tlsn-core = { git = "https://github.com/tlsnotary/tlsn", rev = "v0.1.0-alpha.5" }
# tlsn-verifier = { git = "https://github.com/tlsnotary/tlsn", rev = "v0.1.0-alpha.5" }
# getrandom = { version = "0.2", features = ["custom"] }
# ring = { version = "0.17", features = ["wasm32_unknown_unknown_js"] }
